# fly.toml app configuration file generated for backend-summer-frog-7467 on 2025-06-12T20:40:58-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-summer-frog-7467'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
